// src/rules/schema.rs
// Generates Prisma schema from ResolvedProgram.
// This is the first real codegen step — deterministic, no LLM.

use crate::rules::{ResolvedProgram, ResolvedEntity, ResolvedField};
use crate::rules::field_types::FieldType;

/// Generate a complete Prisma schema string
pub fn generate_prisma(program: &ResolvedProgram) -> String {
    let mut out = String::new();

    // Header
    out.push_str(r#"// This file was generated by spokec. Do not edit manually.
// Re-run `spokec build` to regenerate.

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

"#);

    // User model — always generated if auth is present
    if program.auth.is_some() {
        out.push_str(&generate_user_model(program));
        out.push('\n');
    }

    // App entities
    for entity in &program.entities {
        out.push_str(&generate_model(entity, program));
        out.push('\n');
    }

    out
}

fn generate_user_model(program: &ResolvedProgram) -> String {
    let mut m = String::new();
    m.push_str("model User {\n");
    m.push_str("  id            String    @id @default(cuid())\n");
    m.push_str("  createdAt     DateTime  @default(now())\n");
    m.push_str("  updatedAt     DateTime  @updatedAt\n");
    m.push_str("  email         String    @unique\n");
    m.push_str("  name          String?\n");

    if let Some(auth) = &program.auth {
        if auth.email_password {
            m.push_str("  password      String?\n");
        }
        if auth.magic_link {
            m.push_str("  magicToken    String?\n");
            m.push_str("  magicExpiry   DateTime?\n");
        }
        if !auth.oauth_providers.is_empty() {
            m.push_str("  oauthProvider String?\n");
            m.push_str("  oauthId       String?\n");
        }
    }

    m.push_str("  role          String    @default(\"user\")\n");
    m.push_str("  emailVerified Boolean   @default(false)\n");

    // Add relations to all entities that have a userId field
    for entity in &program.entities {
        let has_user_relation = entity.fields.iter().any(|f| {
            matches!(&f.field_type, FieldType::ForeignKey { to } if to == "user")
        });
        if has_user_relation {
            let name = &entity.name;
            let table = entity.table.clone();
            m.push_str(&format!("  {}s          {}[]  @relation(\"UserTo{}\")\n",
                table, name, name));
        }
    }

    m.push_str("  @@map(\"users\")\n");
    m.push_str("}\n");
    m
}

fn generate_model(entity: &ResolvedEntity, program: &ResolvedProgram) -> String {
    let mut m = String::new();
    m.push_str(&format!("model {} {{\n", entity.name));
    m.push_str("  id        String    @id @default(cuid())\n");

    for field in &entity.fields {
        m.push_str(&format!("  {}\n", prisma_field_line(field)));
    }

    if entity.has_timestamps {
        m.push_str("  createdAt DateTime  @default(now())\n");
        m.push_str("  updatedAt DateTime  @updatedAt\n");
    }

    // Ownership relation — if there's a userId, add User relation
    let user_field = entity.fields.iter().find(|f| {
        matches!(&f.field_type, FieldType::ForeignKey { to } if to == "user")
    });

    if program.auth.is_some() && user_field.is_none() {
        // Auto-add userId for user-owned entities
        m.push_str("  userId    String\n");
        m.push_str("  user      User      @relation(\"UserTo");
        m.push_str(&entity.name);
        m.push_str("\", fields: [userId], references: [id])\n");
    } else if let Some(uf) = user_field {
        m.push_str(&format!("  user      User      @relation(\"UserTo{}\", fields: [{}], references: [id])\n",
            entity.name, uf.name));
    }

    m.push_str(&format!("  @@map(\"{}s\")\n", entity.table));
    m.push_str("}\n");
    m
}

fn prisma_field_line(field: &ResolvedField) -> String {
    let prisma_type = field.field_type.to_prisma();
    let nullable    = if field.required { "" } else { "?" };
    let unique_attr = if field.unique { " @unique" } else { "" };

    let default_attr = match &field.field_type {
        FieldType::Boolean   => " @default(false)".to_string(),
        FieldType::Status    => " @default(\"pending\")".to_string(),
        _                    => field.default.as_ref()
            .map(|d| format!(" @default({})", d))
            .unwrap_or_default(),
    };

    let map_attr = if field.name.contains('_') {
        format!(" @map(\"{}\")", field.name)
    } else {
        String::new()
    };

    // Camel case the Prisma field name
    let prisma_name = crate::rules::to_camel_case(&field.name);

    format!(
        "{:<16}{}{:<12}{}{}{}",
        prisma_name,
        prisma_type,
        nullable,
        unique_attr,
        default_attr,
        map_attr,
    )
}

/// Generate TypeScript types from resolved entities
pub fn generate_typescript_types(program: &ResolvedProgram) -> String {
    let mut out = String::new();
    out.push_str("// Generated by spokec — do not edit\n\n");

    for entity in &program.entities {
        out.push_str(&format!("export interface {} {{\n", entity.name));
        out.push_str("  id: string;\n");

        for field in &entity.fields {
            let ts_type  = field.field_type.to_typescript();
            let nullable = if field.required { "" } else { "?" };
            let name     = crate::rules::to_camel_case(&field.name);

            if !field.private {
                out.push_str(&format!("  {}{}: {};\n", name, nullable, ts_type));
            }
        }

        out.push_str("  createdAt: Date;\n");
        out.push_str("  updatedAt: Date;\n");
        out.push_str("}\n\n");

        // Create input type
        out.push_str(&format!("export interface Create{}Input {{\n", entity.name));
        for field in &entity.fields {
            if !field.private {
                let ts_type  = field.field_type.to_typescript();
                let nullable = if field.required { "" } else { "?" };
                let name     = crate::rules::to_camel_case(&field.name);
                out.push_str(&format!("  {}{}: {};\n", name, nullable, ts_type));
            }
        }
        out.push_str("}\n\n");
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rules::{ResolvedAuth, ResolvedField};
    use crate::rules::field_types::FieldType;

    fn make_program() -> ResolvedProgram {
        ResolvedProgram {
            app_name: "Todo".to_string(),
            auth: Some(ResolvedAuth {
                email_password: true,
                magic_link: false,
                oauth_providers: vec![],
                session_days: 30,
                login_redirect: "/dashboard".to_string(),
                logout_redirect: "/login".to_string(),
            }),
            entities: vec![ResolvedEntity {
                name: "Task".to_string(),
                table: "task".to_string(),
                fields: vec![
                    ResolvedField {
                        name: "title".to_string(),
                        field_type: FieldType::String { max_len: Some(255) },
                        required: true,
                        unique: false,
                        private: false,
                        indexed: false,
                        default: None,
                        validation: vec![],
                    },
                    ResolvedField {
                        name: "deadline".to_string(),
                        field_type: FieldType::DateTime,
                        required: false,
                        unique: false,
                        private: false,
                        indexed: false,
                        default: None,
                        validation: vec![],
                    },
                ],
                has_timestamps: true,
                has_soft_delete: false,
            }],
            actions: vec![],
            pages: vec![],
            triggers: vec![],
        }
    }

    #[test]
    fn test_prisma_has_user_model() {
        let program = make_program();
        let schema = generate_prisma(&program);
        assert!(schema.contains("model User"));
        assert!(schema.contains("model Task"));
    }

    #[test]
    fn test_prisma_has_timestamps() {
        let program = make_program();
        let schema = generate_prisma(&program);
        assert!(schema.contains("createdAt"));
        assert!(schema.contains("updatedAt"));
    }

    #[test]
    fn test_typescript_types() {
        let program = make_program();
        let types = generate_typescript_types(&program);
        assert!(types.contains("export interface Task"));
        assert!(types.contains("export interface CreateTaskInput"));
    }
}
