// src/codegen/api_routes.rs
// Generates Next.js App Router API route handlers for each entity

use crate::rules::{ResolvedEntity, ResolvedAction, OwnershipKind, ActionKind};
use crate::rules::to_pascal_case;

/// GET /api/tasks — list
/// POST /api/tasks — create
pub fn generate_list_create(entity: &ResolvedEntity, actions: &[&ResolvedAction]) -> String {
    let name        = &entity.name;
    let table       = &entity.table;
    let table_plural= format!("{}s", table);
    let name_lower  = table;

    let can_create = actions.iter().any(|a| matches!(a.kind, ActionKind::Create));
    let can_list   = actions.iter().any(|a| matches!(a.kind, ActionKind::List | ActionKind::Read));

    let list_ownership = actions.iter()
        .find(|a| matches!(a.kind, ActionKind::List | ActionKind::Read | ActionKind::Create))
        .map(|a| &a.ownership)
        .cloned()
        .unwrap_or(OwnershipKind::All);

    let list_where = match list_ownership {
        OwnershipKind::Own => "    where: { userId: session?.user?.id as string },\n".to_string(),
        _                  => String::new(),
    };

    let auth_check = match list_ownership {
        OwnershipKind::Own => "  if (!session) return NextResponse.json({ error: \"Unauthorized\" }, { status: 401 });\n",
        _                  => "",
    };

    let list_handler = format!(r#"export async function GET(req: NextRequest) {{
  const session = await getServerSession(authOptions);
  {auth_check}
  const items = await prisma.{name_lower}.findMany({{
    {list_where}orderBy: {{ createdAt: "desc" }},
  }});
  return NextResponse.json(items);
}}"#);

    let create_handler = if can_create {
        // Get required fields (non-private, non-auto)
        let fields: Vec<_> = entity.fields.iter()
            .filter(|f| !f.private && f.name != "id")
            .map(|f| format!("    {}: body.{},", f.name, f.name))
            .collect();
        let fields_str = fields.join("\n");

        format!(r#"export async function POST(req: NextRequest) {{
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({{ error: "Unauthorized" }}, {{ status: 401 }});
  const body = await req.json();
  const item = await prisma.{name_lower}.create({{
    data: {{
{fields_str}
      userId: session.user?.id as string,
    }},
  }});
  return NextResponse.json(item, {{ status: 201 }});
}}"#)
    } else {
        String::new()
    };

    format!(r#"// Generated by spokec
import {{ NextRequest, NextResponse }} from "next/server";
import {{ getServerSession }} from "next-auth";
import {{ authOptions }} from "@/lib/auth";
import {{ prisma }} from "@/lib/db";

{list_handler}

{create_handler}
"#)
}

/// GET /api/tasks/[id]
/// PUT /api/tasks/[id]
/// DELETE /api/tasks/[id]
pub fn generate_get_update_delete(entity: &ResolvedEntity, actions: &[&ResolvedAction]) -> String {
    let table     = &entity.table;
    let name_lower= table;

    let can_update = actions.iter().any(|a| matches!(a.kind, ActionKind::Update));
    let can_delete = actions.iter().any(|a| matches!(a.kind, ActionKind::Delete));

    // Ownership check string
    let own_check = r#"  if (item.userId !== session?.user?.id && session?.user?.role !== "admin") {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }"#;

    let get_handler = format!(r#"export async function GET(req: NextRequest, {{ params }}: {{ params: {{ id: string }} }}) {{
  const item = await prisma.{name_lower}.findUnique({{ where: {{ id: params.id }} }});
  if (!item) return NextResponse.json({{ error: "Not found" }}, {{ status: 404 }});
  return NextResponse.json(item);
}}"#);

    let update_handler = if can_update { format!(r#"export async function PUT(req: NextRequest, {{ params }}: {{ params: {{ id: string }} }}) {{
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({{ error: "Unauthorized" }}, {{ status: 401 }});
  const item = await prisma.{name_lower}.findUnique({{ where: {{ id: params.id }} }});
  if (!item) return NextResponse.json({{ error: "Not found" }}, {{ status: 404 }});
{own_check}
  const body = await req.json();
  const updated = await prisma.{name_lower}.update({{
    where: {{ id: params.id }},
    data: body,
  }});
  return NextResponse.json(updated);
}}"#) } else { String::new() };

    let delete_handler = if can_delete { format!(r#"export async function DELETE(req: NextRequest, {{ params }}: {{ params: {{ id: string }} }}) {{
  const session = await getServerSession(authOptions);
  if (!session) return NextResponse.json({{ error: "Unauthorized" }}, {{ status: 401 }});
  const item = await prisma.{name_lower}.findUnique({{ where: {{ id: params.id }} }});
  if (!item) return NextResponse.json({{ error: "Not found" }}, {{ status: 404 }});
{own_check}
  await prisma.{name_lower}.delete({{ where: {{ id: params.id }} }});
  return NextResponse.json({{ success: true }});
}}"#) } else { String::new() };

    format!(r#"// Generated by spokec
import {{ NextRequest, NextResponse }} from "next/server";
import {{ getServerSession }} from "next-auth";
import {{ authOptions }} from "@/lib/auth";
import {{ prisma }} from "@/lib/db";

{get_handler}

{update_handler}

{delete_handler}
"#)
}
