// src/codegen/nextauth.rs
use crate::rules::ResolvedProgram;

pub fn generate(program: &ResolvedProgram) -> String {
    let auth = match &program.auth {
        Some(a) => a,
        None    => return String::new(),
    };

    let mut providers = String::new();

    if auth.email_password {
        providers.push_str(r#"
    CredentialsProvider({
      name: "credentials",
      credentials: {
        email:    { label: "Email",    type: "email" },
        password: { label: "Password", type: "password" },
      },
      async authorize(credentials) {
        if (!credentials?.email || !credentials?.password) return null;
        const user = await prisma.user.findUnique({
          where: { email: credentials.email },
        });
        if (!user || !user.password) return null;
        const valid = await bcrypt.compare(credentials.password, user.password);
        if (!valid) return null;
        return { id: user.id, email: user.email, name: user.name, role: user.role };
      },
    }),"#);
    }

    if auth.oauth_providers.contains(&"google".to_string()) {
        providers.push_str(r#"
    GoogleProvider({
      clientId:     process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    }),"#);
    }

    if auth.oauth_providers.contains(&"github".to_string()) {
        providers.push_str(r#"
    GitHubProvider({
      clientId:     process.env.GITHUB_CLIENT_ID!,
      clientSecret: process.env.GITHUB_CLIENT_SECRET!,
    }),"#);
    }

    let imports = build_imports(auth);
    let session_days = auth.session_days;
    let login_redirect = &auth.login_redirect;
    let logout_redirect = &auth.logout_redirect;

    format!(r#"// Generated by spokec
{imports}

export const authOptions: NextAuthOptions = {{
  providers: [{providers}
  ],
  session: {{
    strategy: "jwt",
    maxAge:   {session_days} * 24 * 60 * 60,
  }},
  callbacks: {{
    async jwt({{ token, user }}) {{
      if (user) {{ token.id = user.id; token.role = (user as any).role ?? "user"; }}
      return token;
    }},
    async session({{ session, token }}) {{
      if (session.user) {{
        (session.user as any).id   = token.id as string;
        (session.user as any).role = token.role as string;
      }}
      return session;
    }},
  }},
  pages: {{
    signIn:  "/login",
    signOut: "{logout_redirect}",
    error:   "/login",
  }},
}};

export default NextAuth(authOptions);
"#)
}

fn build_imports(auth: &crate::rules::ResolvedAuth) -> String {
    let mut imports = String::new();
    imports.push_str("import NextAuth, { NextAuthOptions } from \"next-auth\";\n");
    imports.push_str("import { prisma } from \"@/lib/db\";\n");

    if auth.email_password {
        imports.push_str("import CredentialsProvider from \"next-auth/providers/credentials\";\n");
        imports.push_str("import bcrypt from \"bcryptjs\";\n");
    }
    if auth.oauth_providers.contains(&"google".to_string()) {
        imports.push_str("import GoogleProvider from \"next-auth/providers/google\";\n");
    }
    if auth.oauth_providers.contains(&"github".to_string()) {
        imports.push_str("import GitHubProvider from \"next-auth/providers/github\";\n");
    }

    imports
}

pub fn route_handler() -> String {
r#"import NextAuth from "next-auth";
import { authOptions } from "@/lib/auth";
const handler = NextAuth(authOptions);
export { handler as GET, handler as POST };
"#.to_string()
}

pub fn signup_handler() -> String {
r#"import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import bcrypt from "bcryptjs";

export async function POST(req: NextRequest) {
  const { name, email, password } = await req.json();
  if (!email || !password) return NextResponse.json({ error: "Missing fields" }, { status: 400 });

  const exists = await prisma.user.findUnique({ where: { email } });
  if (exists) return NextResponse.json({ error: "Email already in use" }, { status: 400 });

  const hashed = await bcrypt.hash(password, 12);
  const user = await prisma.user.create({
    data: { name, email, password: hashed },
  });

  return NextResponse.json({ id: user.id, email: user.email });
}
"#.to_string()
}
