// src/codegen/pages.rs
use crate::rules::{ResolvedPage, ResolvedProgram, OwnershipKind};
use crate::ast::AccessLevel;
use crate::rules::to_pascal_case;

pub fn generate_page(page: &ResolvedPage, _program: &ResolvedProgram) -> String {
    let name = &page.name;
    let component = to_pascal_case(&name.replace(' ', "_")) + "Page";

    let auth_guard = match &page.access {
        AccessLevel::Public       => String::new(),
        AccessLevel::RequireLogin => "  const session = await getServerSession(authOptions);\n  if (!session) redirect(\"/login\");".to_string(),
        AccessLevel::RequireRole(r)=> format!("  const session = await getServerSession(authOptions);\n  if (!session) redirect(\"/login\");\n  if ((session.user as any)?.role !== \"{r}\") redirect(\"/\");"),
    };

    let has_auth  = !auth_guard.is_empty();
    let has_data  = !page.queries.is_empty();

    let mut fetches = String::new();
    let mut jsx     = String::new();

    for (i, q) in page.queries.iter().enumerate() {
        let var  = format!("items{}", i);
        let where_ = if matches!(q.ownership, OwnershipKind::Own) {
            "    where: { userId: (session?.user as any)?.id },\n".to_string()
        } else { String::new() };
        let order = q.order_by.as_ref()
            .map(|(f, d)| format!("    orderBy: {{ {f}: \"{}\"}},\n", d.to_lowercase()))
            .unwrap_or_default();
        let take = q.limit.map(|n| format!("    take: {n},\n")).unwrap_or_default();
        fetches.push_str(&format!("  const {var} = await prisma.{}.findMany({{\n{where_}{order}{take}}});\n", q.entity));

        jsx.push_str(&format!(r#"      <div className="space-y-3">
        {{{var}.map((item: any) => (
          <div key={{item.id}} className="bg-white border rounded-xl p-4 shadow-sm">
            <p className="font-medium">{{item.title ?? item.name ?? item.id}}</p>
            {{item.deadline && <p className="text-sm text-gray-500">Due: {{new Date(item.deadline).toLocaleDateString()}}</p>}}
            {{item.status && <span className="mt-1 inline-block px-2 py-0.5 rounded-full text-xs bg-gray-100">{{item.status}}</span>}}
          </div>
        ))}}
        {{{var}.length === 0 && <p className="text-gray-400 text-center py-8">Nothing here yet.</p>}}
      </div>
"#));
    }

    let auth_import = if has_auth {
        "import { getServerSession } from \"next-auth\";\nimport { authOptions } from \"@/lib/auth\";\nimport { redirect } from \"next/navigation\";\n"
    } else { "" };
    let db_import = if has_data { "import { prisma } from \"@/lib/db\";\n" } else { "" };

    format!(r#"// Generated by spokec
{auth_import}{db_import}
export default async function {component}() {{
{auth_guard}
{fetches}
  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <h1 className="text-2xl font-bold mb-6">{name}</h1>
{jsx}    </div>
  );
}}
"#)
}
